name: Сообщение о баге
description: Сообщение о баге, чтобы помочь нам найти и исправить баги!
title: "[Баг]"
labels: [баг]
body:
- type: checkboxes
  attributes:
    label: Перед отправкой
    options:
    - label: Я не нашел существующих проблем, соответствующих моему багу
      required: true
    - label: Я полностью перезапустил Discord и проверил, остаеться ли баг
      required: true
- type: textarea
  attributes:
    label: Опишите баг!
    description: |
      Четкое и понятное описание бага.

      Подсказка: Вы можете прикрепить изображения, нажав на это поле, чтобы выделить его, а затем перетащив файлы.
  validations:
    required: true
- type: textarea
  attributes:
    label: Ожидаемое поведение
    description: Четкое и понятное описание того, что вы ожидали увидеть.
  validations:
    required: true
- type: textarea
  attributes:
    label: Шаги для воспроизведения
    description: Шаги для воспроизведения поведения.
    placeholder: |
      1. Открыть настройки
      2. Зайти во вкладку "Устройства"
      3. Прокрутить вниз
      4. Увидеть баг...
  validations:
    required: true
- type: dropdown
  attributes:
    label: Операционная система
    options:
      - Windows
      - Linux
      - MacOS
  validations:
    required: true
